INSERT INTO produto (id, nome, descricao) VALUES
  (1, 'Mouse Gamer', 'Mouse com 6 botões e RGB'),
  (2, 'Notebook', 'Notebook 15" 16GB RAM'),
  (3, 'Headset', 'Headset com cancelamento de ruído'),
  (4, 'Teclado Mecânico', 'Teclado mecânico switch blue'),
  (5, 'Monitor', 'Monitor 24" Full HD 144hz'),
  (6, 'Webcam', 'Webcam 1080p com microfone'),
  (7, 'SSD', 'SSD 500GB NVMe'),
  (8, 'Memória RAM', 'Memória RAM 16GB DDR4'),
  (9, 'Placa de Vídeo', 'GPU 8GB GDDR6'),
  (10, 'Processador', 'Processador 8 núcleos 3.8GHz'),
  (11, 'Fonte', 'Fonte 650W 80 Plus Bronze'),
  (12, 'Gabinete', 'Gabinete mid-tower com janela lateral'),
  (13, 'Placa Mãe', 'Placa mãe ATX socket AM5'),
  (14, 'Cooler', 'Cooler para processador 120mm'),
  (15, 'Hub USB', 'Hub USB 3.0 com 7 portas'),
  (16, 'Suporte Monitor', 'Suporte articulado para monitor'),
  (17, 'Mousepad', 'Mousepad XL 90x40cm'),
  (18, 'Caixa de Som', 'Caixa de som 2.1 com subwoofer'),
  (19, 'Nobreak', 'Nobreak 1200VA com 8 tomadas'),
  (20, 'Leitor de Cartão', 'Leitor de cartão SD e microSD USB');